### PR TITLE
GameClass + EditText in CreateRoomActivity.java

### PR DESCRIPTION
**Pull request by KamilDevelopments**

### CODE REVIEW

**Review by Vertonowsky — CHANGES_REQUESTED** [review]
Add input for user's nickname in CreateRoomActivity. Besides uuid, every player is identified by his unique nickname. 
Also it would be nice to create labels next to inputs + make all of the inputs the same static width. There should also be a characters limitation.

**Review by kestivvi — APPROVED** [review]
Please, provide descriptions in your pull requests in the future.

**Comment by KamilDevelopments** [comment]
> Add input for user's nickname in CreateRoomActivity. Besides uuid, every player is identified by his unique nickname. 
> Also it would be nice to create labels next to inputs + make all of the inputs the same static width. There should also be a characters limitation. 

Make one version how it should be done, than Ill fix it

**Comment by Vertonowsky** [comment]
> > Add input for user's nickname in CreateRoomActivity. Besides uuid, every player is identified by his unique nickname.
> > Also it would be nice to create labels next to inputs + make all of the inputs the same static width. There should also be a characters limitation.
> 
> Make one version how it should be done, than Ill fix it

that's the version how it should be done.

**Review by Vertonowsky — APPROVED** [review]

**Pull request merged**
