### PR TITLE
added new graphics

### LINKED ISSUE #49: Change the graphics of aristocrats and add some graphics for cards
Replace some pics of aristocrats(min resolution 56x56px) in the drawable direction and create new graphics for cards (min resolution 80x48px)

### PR DESCRIPTION
**Pull request by agatamrnw**
I've replaced some graphics of aristocrats and also added graphics for closed cards and pictures that may be used in opened cards views

### CODE REVIEW

**Comment by kestivvi** [comment]
I don't get the naming. Files named "noble" are the landscape? And the actual nobles are named "pic.

**Comment by agatamrnw** [comment]
I've changed the naming also in the part where old names were used

**Review by kestivvi — DISMISSED** [review]

**Review by KamilDevelopments — DISMISSED** [review]

**Review by Vertonowsky — CHANGES_REQUESTED** [review]
In my opinion images use too many various design styles. I would suggest creating images with the same style.

**Comment by Vertonowsky** [comment]
> In my opinion images use too many various design styles. I would suggest creating images with the same style.

Also consider, that some images are actually big (almost 1.5MB). We don't need such a big resolution since on phones we won't see it due ti small screen.

**Comment by kestivvi** [comment]
Imo 1.5 MB is not that large at all.

**Comment by agatamrnw** [comment]
Now all the pictures of nobles are in same style. Also backgroung images were compressed

**Review by kestivvi — APPROVED** [review]

**Review by Vertonowsky — APPROVED** [review]

**Pull request merged**
