### PR TITLE
implemented basic Tutorial layout

### LINKED ISSUE #92: Tutorial activity
One of the requirements for the project is to create a tutorial for the game. I propose that we create the tutorial as an activity within our application, and add a button in the MainMenu to access it.

Goals:
- Create an activity for the tutorial, which can initially be empty or have a basic structure. (*The content will be addressed in another issue*)
- Develop styles for the tutorial activity. (*Another person in the same branch who is proficient in this area can handle this task*)
- Add a button in the MainMenu that will allow users to access the tutorial.
- Ensure that the button is styled appropriately to conform to the MainMenu style. (*Another person in the same branch who is proficient in this area can handle this task*)

### PR DESCRIPTION
**Pull request by KamilDevelopments**
implemented basic Tutorial layout

### CODE REVIEW

**Comment by agatamrnw** [comment]
I've added content to TutorialActivity such as game rules. Haven't added onboarding yet cause I'm not sure what pictures will be used

**Comment by agatamrnw** [comment]
I've complited tutorial activity with some screenshots and graphics

**Review by kestivvi — CHANGES_REQUESTED** [review]
Error occurs while building the app: Found item String/card_title more than one time

Probably duplicate entries in the pl-rPL/strings.xml
image

Also I can see some typos:
image

**Review by kestivvi — APPROVED** [review]
Astonishing 👏✌️🥳🎖️

**Pull request merged**
