### PR TITLE
17 uiux design and development

### LINKED ISSUE #17: UI/UX design and development
We need to create a user-friendly interface and add graphics to them.

### PR DESCRIPTION
**Pull request by KamilDevelopments**
Added basic structure of GameRoom activity (without much styling for now), there is a problem tho, The layout from Figma won't fit so we need to change it a little bit, any Ideas?
The layout looks like this rn:
image

### CODE REVIEW

**Comment by kestivvi** [comment]
Maybe some screen width aware styles needs to be implemented. If screen is not wide enough then those reserved cards on the left will be available by clicking some "Extend/Show" button on the left to pull out something like a drawer.

Here's some poor graphic idea sketch.




It's one of the solutions. Generally, our lecturer said that we should utilise the power gestures on the android. So instead of button we could use slide gesture.

**Comment by EaZZyHK** [comment]
Actually, if we remove those 3 upper rectangles (those are piles of cards, which in my opinion are useless) we could bring all nobles to the top and rotate them so they are horizontally oriented. That should give us a little bit more space.

**Comment by kestivvi** [comment]
Decks (piles of card) could be used when you want to make reservation of an unknown card from the deck. For example to make a reservation click on the pile of gold tokens and then click on a card you want to reserve or click on a deck from which you want to get a card. That's one scenario when those decks can be used.

You can implement reservation without seeing decks on the table. One idea that comes to my mind is the following. Click on pile of gold tokens, then the window with 2 options will show up. First option is to make a reservation of the card from the table. Second is to make reservation from the deck, clicking it will show up another window with 3 options for each tier of decks.

**Comment by Vertonowsky** [comment]
I suggest making only the main dashboard + all players visible on game start. We can show player points next to their icon. 



If you click on player icon, then you will see all of his tokens, cards and points in total.
It would look like something similar to this:


Then we wouldn't have a problem with missing space

**Comment by KamilDevelopments** [comment]
Added base View of Game class. It still needs some work + styling, but I'll add it next week. Also removed Toolbar.hide() from all activities and added it to themes

**Review by EaZZyHK — APPROVED** [review]

**Review by Vertonowsky — APPROVED** [review]

**Pull request merged**
