### PR TITLE
Make websocket client more programmer friendly

### PR DESCRIPTION
**Pull request by kestivvi**
Now interaction through websockets in much easier. There is global singleton class CustomWebSocketClient. You can send messages with it. The best would be if you send `UserMessage` object only. It minimalizes risk of error. 

Now server repo is set as dependency in this project. It's done with jitpack. Unfortunately, if you want to see new changes on the server repo in dependency you have to go to [jitpack site](https://jitpack.io/#Splendor-Mobile-Game/ServerSide) and search for our server github repository, then find develop branch and click `Get it` so the new version will be built. Then in android studio you have to refresh your dependencies in Gradle tab. Click RMB on root of the project and then refresh.

image

Everytime when you want to send message to the server check if that reaction requires some data as an input, then you can instantiate that dataclass and build a `UserMessage`, then use `CustomWebSocketClient.getInstance()` to get and instance of websocket client and then `send()` method on that, as argument you have to pass the `UserMessage`.

There is new package `reactions`, those are mirror of the server reactions but those react to the server messages. If you want to send the message to the sever in those reaction you can just return the `UserMessage`, if not then null. 

The `Model` class is something like `Database` class on the server. `Model` stores all the data to save the current context of the state of the application.

### CODE REVIEW

**Comment by kestivvi** [comment]
See related [pull request](https://github.com/Splendor-Mobile-Game/ServerSide/pull/44) on the server side. Those two requests must be merged simultaneously to work.

**Comment by kestivvi** [comment]
If you want to work directly on this branch you need to change `build.gradle` file a little bit.

Just change the line 
```
implementation 'com.github.Splendor-Mobile-Game:ServerSide:develop-SNAPSHOT'
```
to 
```
implementation 'com.github.Splendor-Mobile-Game:ServerSide:adjust-to-the-client-perspective-SNAPSHOT'
```

**Comment by kestivvi** [comment]
There is a way of automatic jitpack refresh after each pull request by using github actions. I have found [some article](https://dev.to/cicirello/ahead-of-time-jitpack-builds-with-custom-groupid-via-github-actions-55cp) about that.

**Review by EaZZyHK — APPROVED** [review]

**Review by Vertonowsky — APPROVED** [review]
Ok

**Pull request merged**
